'use strict';
const {randomUUID}=require('crypto');const {MAX_SNAPSHOTS}=require('./testModel');const {assertUuid,assertRevision,assertJsonSize,validateCheckpoint,MAX_CHECKPOINT}=require('./testValidation');
const clone=x=>JSON.parse(JSON.stringify(x));
function createAttemptCheckpointService({store}={}){
 if(!store)throw Error('store obligatorio');let root=store.load();const persist=()=>store.save(root);
 function owner(attemptId,accountPlayerId,testId){assertUuid(attemptId,'attemptId');assertUuid(accountPlayerId,'accountPlayerId');assertUuid(testId,'testId');const a=root.attempts.find(x=>x.attemptId===attemptId);if(!a)throw Error('intento no encontrado');if(a.accountPlayerId!==accountPlayerId)throw Error('propietario invalido');if(a.testId!==testId)throw Error('testId inconsistente');if(['deleted','restarted'].includes(a.status))throw Error('intento no disponible');return a;}
 function list(attemptId){return root.checkpoints.filter(c=>c.attemptId===attemptId).sort((a,b)=>a.revision-b.revision);}
 function cleanupAttemptCheckpoints(attemptId){const rows=list(attemptId);while(rows.length>MAX_SNAPSHOTS){const old=rows.shift();root.checkpoints=root.checkpoints.filter(c=>c!==old);}}
 function saveAttemptCheckpoint({attemptId,testId,accountPlayerId,revision,eventId,checkpointId,...data}){owner(attemptId,accountPlayerId,testId);assertUuid(eventId,'eventId');if(checkpointId!==undefined)assertUuid(checkpointId,'checkpointId');assertRevision(revision);if(data.index===undefined||!Number.isInteger(data.index)||data.index<0)throw Error('index invalido');const duplicate=root.checkpoints.find(c=>c.eventId===eventId);if(duplicate)return {checkpoint:clone(duplicate),duplicate:true};const prior=list(attemptId);if(prior.length&&revision<=prior.at(-1).revision)throw Error('revision antigua');const checkpoint={checkpointId:checkpointId||randomUUID(),attemptId,testId,accountPlayerId,index:data.index,revision,eventId,occurredAt:data.occurredAt||new Date().toISOString(),answers:Array.isArray(data.answers)?data.answers:[],pendingItems:Array.isArray(data.pendingItems)?data.pendingItems:[],correct:Number(data.correct)||0,incorrect:Number(data.incorrect)||0,effectiveTime:Number(data.effectiveTime)||0,attemptState:data.attemptState||'in_progress',progress:data.progress&&typeof data.progress==='object'?clone(data.progress):{}};validateCheckpoint(checkpoint);assertJsonSize(checkpoint,MAX_CHECKPOINT,'checkpoint');root.checkpoints.push(checkpoint);cleanupAttemptCheckpoints(attemptId);persist();return {checkpoint:clone(checkpoint),duplicate:false};}
 function getLatestAttemptCheckpoint(input){owner(input.attemptId,input.accountPlayerId,input.testId);const rows=list(input.attemptId);return rows.length?clone(rows.at(-1)):null;}
 function getAttemptCheckpointByRevision(input){owner(input.attemptId,input.accountPlayerId,input.testId);assertRevision(input.revision);const row=list(input.attemptId).find(c=>c.revision===input.revision);return row?clone(row):null;}
 function validateCheckpointOwnership(input){owner(input.attemptId,input.accountPlayerId,input.testId);return true;}
 return {saveAttemptCheckpoint,getLatestAttemptCheckpoint,getAttemptCheckpointByRevision,validateCheckpointOwnership,cleanupAttemptCheckpoints};
}
module.exports={createAttemptCheckpointService};
