'use strict';
const {randomUUID}=require('crypto');
const {assertUuid}=require('./testValidation');
const clone=value=>JSON.parse(JSON.stringify(value));
const now=()=>new Date().toISOString();
const OFFICIAL_STATES=new Set(['finished']);
const REJECTED_STATES=new Set(['pending','started','in_progress','paused','disconnected','reconnected','incomplete','restarted','deleted','reopened']);
function createOfficialAttemptService({root,loadRanking=()=>[],saveRanking=()=>{},persist=()=>{},actor='admin'}={}){
  if(!root)throw Error('root obligatorio');
  if(!Array.isArray(root.officialAttempts))root.officialAttempts=[];
  if(!Array.isArray(root.rankingPublications))root.rankingPublications=[];
  const audit=(testId,attemptId,action,eventId,reason,metadata={})=>{root.events.push({eventId,testId,attemptId,actor,action,reason,revision:1,occurredAt:now(),metadata});};
  const findTest=testId=>{assertUuid(testId,'testId');const test=(root.tests||[]).find(x=>x.testId===testId);if(!test)throw Error('prueba no encontrada');return test;};
  const findAttempt=(testId,attemptId)=>{findTest(testId);assertUuid(attemptId,'attemptId');const attempt=(root.attempts||[]).find(x=>x.attemptId===attemptId);if(!attempt)throw Error('intento no encontrado');if(attempt.testId!==testId)throw Error('testId inconsistente');return attempt;};
  function validateRequest({testId,attemptId,accountPlayerId,actor:requestActor,eventId,reason}={}){findTest(testId);assertUuid(attemptId,'attemptId');assertUuid(eventId,'eventId');if(requestActor!==actor)throw Error('actor no autorizado');if(accountPlayerId!==undefined)assertUuid(accountPlayerId,'accountPlayerId');if(typeof reason!=='string'||!reason.trim())throw Error('motivo obligatorio');}
  function eventFor(eventId,testId,attemptId,action,reason){const event=(root.events||[]).find(x=>x.eventId===eventId);if(!event)return null;const same=event.testId===testId&&event.attemptId===attemptId&&event.action===action&&(!reason||event.reason===reason.trim()); if(!same)throw Error('eventId contradictorio');return event;}
  function resultFor(attempt){const result=(root.results||[]).find(x=>x.attemptId===attempt.attemptId&&x.testId===attempt.testId);if(!result)throw Error('resultado no encontrado');if(result.accountPlayerId!==attempt.accountPlayerId)throw Error('resultado inconsistente');if(result.complete===false||!Number.isFinite(Number(result.score))||!Number.isFinite(Number(result.correct))||!Number.isFinite(Number(result.incorrect)))throw Error('resultado invalido');return result;}
  function safeOfficial(item){return item?{officialAttemptId:item.officialAttemptId,testId:item.testId,attemptId:item.attemptId,accountPlayerId:item.accountPlayerId,resultId:item.resultId,officialAt:item.officialAt,actor:item.actor,reason:item.reason}:null;}
  function officialFor(testId,accountPlayerId){return root.officialAttempts.find(x=>x.testId===testId&&x.accountPlayerId===accountPlayerId)||null;}
  function officialResult(item){return clone(item.resultSnapshot);}
  function officialize(input={}){
    validateRequest(input);const {testId,attemptId,accountPlayerId,eventId,reason}=input;const attempt=findAttempt(testId,attemptId);if(accountPlayerId!==undefined&&attempt.accountPlayerId!==accountPlayerId)throw Error('intento pertenece a otro alumno');
    const priorEvent=eventFor(eventId,testId,attemptId,'attempt_officialized',reason);if(priorEvent){const existing=root.officialAttempts.find(x=>x.attemptId===attemptId);return {officialAttempt:safeOfficial(existing),duplicate:true};}
    if(!OFFICIAL_STATES.has(attempt.status))throw Error(REJECTED_STATES.has(attempt.status)?'estado no oficializable':'estado invalido');
    const result=resultFor(attempt),existing=officialFor(testId,attempt.accountPlayerId);if(existing&&existing.attemptId!==attemptId)throw Error('ya existe intento oficial');
    const officialAttemptId=existing?.officialAttemptId||attempt.officialAttemptId||randomUUID();const record={officialAttemptId,testId,attemptId,accountPlayerId:attempt.accountPlayerId,resultId:result.resultId,resultSnapshot:clone(result),officialAt:now(),actor,reason:reason.trim()};
    root.officialAttempts.push(record);attempt.official=true;attempt.officialAttemptId=officialAttemptId;attempt.officialAt=record.officialAt;audit(testId,attemptId,'attempt_officialized',eventId,record.reason,{officialAttemptId,resultId:result.resultId});persist();return {officialAttempt:safeOfficial(record),duplicate:false};
  }
  function getOfficialAttempt({testId,attemptId,accountPlayerId}={}){const attempt=findAttempt(testId,attemptId);if(accountPlayerId!==undefined&&attempt.accountPlayerId!==accountPlayerId)throw Error('intento pertenece a otro alumno');return safeOfficial(root.officialAttempts.find(x=>x.attemptId===attemptId)||null);}
  function listOfficialAttempts(testId){findTest(testId);return root.officialAttempts.filter(x=>x.testId===testId).map(safeOfficial);}
  function preparePublication({testId,attemptId}={}){const attempt=findAttempt(testId,attemptId),official=root.officialAttempts.find(x=>x.testId===testId&&x.attemptId===attemptId);if(!official)throw Error('intento no oficial');if(attempt.status!=='finished')throw Error('intento no publicable');const result=officialResult(official);return buildRankingRecord(official,result);}
  function buildRankingRecord(official,result){const snapshot=result.progress?.studentSnapshot||result.studentSnapshot||{};const correct=Number(result.correct)||0,wrong=Number(result.incorrect??result.wrong)||0,total=Number(result.total)||correct+wrong;return {id:official.rankingPublicationId||randomUUID(),name:String(result.name||snapshot.name||'?'),grade:String(result.grade||snapshot.grade||''),score:Number(result.score)||0,correct,wrong,timeout:Number(result.timeout)||0,total,pct:Number(result.pct)|| (total?Math.round(correct/total*100):0),streak:Number(result.streak)||0,gameMode:result.gameMode||'solo',setupMode:result.setupMode||result.gameMode||'solo',mpGameMode:result.mpGameMode||'',gameType:result.gameType||'timed',difficulty:result.difficulty||'',op:result.op||'mult',vs:result.vs||'',tables:Array.isArray(result.tables)?clone(result.tables):[],tblResults:result.tblResults&&typeof result.tblResults==='object'?clone(result.tblResults):{},tableDetail:result.tableDetail&&typeof result.tableDetail==='object'?clone(result.tableDetail):{},stepDetail:result.stepDetail&&typeof result.stepDetail==='object'?clone(result.stepDetail):{},isExam:true,date:new Date().toLocaleDateString('es-MX'),time:new Date().toLocaleTimeString('es-MX',{hour:'2-digit',minute:'2-digit'}),complete:true,testId:official.testId,attemptId:official.attemptId,officialAttemptId:official.officialAttemptId,rankingPublicationId:official.rankingPublicationId||null,publicationType:'official_exam'};}
  function publish(input={}){
    validateRequest(input);const {testId,attemptId,eventId,reason}=input;const official=root.officialAttempts.find(x=>x.testId===testId&&x.attemptId===attemptId);if(!official)throw Error('intento no oficial');const priorEvent=eventFor(eventId,testId,attemptId,'ranking_published',reason);if(priorEvent){const publication=root.rankingPublications.find(x=>x.testId===testId&&x.attemptId===attemptId);return {publication:publication?clone(publication):null,duplicate:true};}const attempt=findAttempt(testId,attemptId);if(attempt.status!=='finished')throw Error('intento no publicable');const previous=root.rankingPublications.find(x=>x.testId===testId&&x.attemptId===attemptId);if(previous)throw Error('publicacion ya existe');const record=buildRankingRecord(official,official.resultSnapshot),rankingPublicationId=record.id;record.rankingPublicationId=rankingPublicationId;official.rankingPublicationId=rankingPublicationId;const ranking=loadRanking();if(ranking.some(x=>x.rankingPublicationId===rankingPublicationId||x.id===rankingPublicationId))throw Error('rankingPublicationId ya existe');saveRanking([record,...(Array.isArray(ranking)?ranking:[])].slice(0,500));const publication={rankingPublicationId,testId,attemptId,officialAttemptId:official.officialAttemptId,accountPlayerId:official.accountPlayerId,publishedAt:now(),actor,reason:reason.trim(),record:clone(record)};root.rankingPublications.push(publication);audit(testId,attemptId,'ranking_published',eventId,publication.reason,{officialAttemptId:official.officialAttemptId,rankingPublicationId});persist();return {publication:clone(publication),duplicate:false};
  }
  function getPublication({testId,attemptId}={}){findAttempt(testId,attemptId);const item=root.rankingPublications.find(x=>x.testId===testId&&x.attemptId===attemptId);return item?{rankingPublicationId:item.rankingPublicationId,testId:item.testId,attemptId:item.attemptId,officialAttemptId:item.officialAttemptId,publishedAt:item.publishedAt,actor:item.actor}:null;}
  return {officialize,getOfficialAttempt,listOfficialAttempts,preparePublication,publish,getPublication};
}
module.exports={createOfficialAttemptService,OFFICIAL_STATES,REJECTED_STATES};
