'use strict';
const {assertUuid}=require('./testValidation');
const states=new Set(['pending','started','in_progress','disconnected','reconnected','finished','incomplete','restarted','reopened','deleted']);const sorts=new Set(['updatedAt','progress','effectiveTime','status']);
function createTestSupervisionService({root,store=null}={}){
 if(!root&&!store)throw Error('root obligatorio');const current=()=>store?store.load():root;const attempts=()=>{const data=current();return Array.isArray(data.attempts)?data.attempts:[];};
 function minimizeAttemptForSupervision(a){const data=current(),cp=(data.checkpoints||[]).filter(c=>c.attemptId===a.attemptId).sort((x,y)=>(y.revision||0)-(x.revision||0))[0],snap=a.progress?.studentSnapshot||{},result=(data.results||[]).find(x=>x.attemptId===a.attemptId&&x.testId===a.testId),hasValidResult=!!result&&result.complete!==false&&Number.isFinite(Number(result.score))&&Number.isFinite(Number(result.correct))&&Number.isFinite(Number(result.incorrect));return Object.freeze({attemptId:a.attemptId,testId:a.testId,accountPlayerId:a.accountPlayerId,name:snap.name||'',grade:snap.grade||'',groupId:a.groupId??snap.grade??null,status:a.status,index:cp?.index??a.progress?.currentIndex??0,progress:a.progress?.progress||{},totalQuestions:cp?.totalQuestions??a.progress?.totalQuestions??0,correct:cp?.correct??a.progress?.correct??0,incorrect:cp?.incorrect??a.progress?.incorrect??0,effectiveTime:cp?.effectiveTime??0,checkpointRevision:cp?.revision??null,checkpointSavedAt:cp?.savedAt||cp?.occurredAt||null,checkpointState:cp?.attemptState||null,updatedAt:a.updatedAt,startedAt:a.startedAt,finishedAt:a.finishedAt,connectionState:a.status==='disconnected'?'disconnected':a.status==='reconnected'?'reconnected':a.status==='finished'?'finished':'connected',checkpointRestored:!!cp,hasValidResult,result:hasValidResult?{resultId:result.resultId,score:result.score,correct:result.correct,incorrect:result.incorrect,total:result.total,complete:result.complete,completedAt:result.completedAt}:null});}
 function filterTestAttempts(rows,{status,groupId,accountPlayerId,connectionState}={}){if(status&&!states.has(status))throw Error('status invalido');if(connectionState&&!['disconnected','reconnected','unknown'].includes(connectionState))throw Error('connectionState invalido');return rows.filter(a=>(!status||a.status===status)&&(!groupId||a.groupId===groupId)&&(!accountPlayerId||a.accountPlayerId===accountPlayerId)&&(!connectionState||a.connectionState===connectionState));}
 function sortTestAttempts(rows,{sort='updatedAt',direction='desc'}={}){if(!sorts.has(sort)||!['asc','desc'].includes(direction))throw Error('orden invalido');return [...rows].sort((a,b)=>{const v=String(a[sort]).localeCompare(String(b[sort]));return direction==='asc'?v:-v;});}
 function listTestAttempts(testId,filters={}){const data=current();assertUuid(testId,'testId');if(!(data.tests||[]).some(t=>t.testId===testId))throw Error('prueba no encontrada');const limit=Math.min(Math.max(Number(filters.limit)||50,1),100);return sortTestAttempts(filterTestAttempts(attempts().filter(a=>a.testId===testId).map(minimizeAttemptForSupervision),filters),filters).slice(0,limit);}
 function getTestAttempt(testId,attemptId){assertUuid(attemptId,'attemptId');const item=listTestAttempts(testId,{limit:100}).find(a=>a.attemptId===attemptId);if(!item)throw Error('intento no encontrado');return item;}
 return {listTestAttempts,getTestAttempt,filterTestAttempts,sortTestAttempts,minimizeAttemptForSupervision};
}
module.exports={createTestSupervisionService};
