'use strict';
const { randomUUID }=require('crypto');
const { assertTransition }=require('./testStateMachine');
const { validateTest,validateAttempt,validateCheckpoint,assertUuid,assertJsonSize,MAX_METADATA }=require('./testValidation');
const SCHEMA_VERSION=1, MAX_SNAPSHOTS=20;
const now=()=>new Date().toISOString(); const id=()=>randomUUID();
function createRoot(){return {schemaVersion:SCHEMA_VERSION,tests:[],assignments:[],attempts:[],checkpoints:[],results:[],events:[]};}
function createTest(input={}){const ts=now();const test={testId:input.testId||id(),schemaVersion:SCHEMA_VERSION,title:input.title||'',description:input.description||'',status:input.status||'draft',configuration:input.configuration||{},creator:input.creator||'',createdAt:input.createdAt||ts,updatedAt:input.updatedAt||ts,scheduledAt:input.scheduledAt||null,startsAt:input.startsAt||null,closesAt:input.closesAt||null,revision:input.revision||1};validateTest(test);return test;}
function createAssignment(input={}){const a={assignmentId:input.assignmentId||id(),testId:input.testId, targetType:input.targetType,groupId:input.groupId||null,accountPlayerId:input.accountPlayerId||null,startsAt:input.startsAt||null,closesAt:input.closesAt||null,createdAt:input.createdAt||now(),revision:input.revision||1};assertUuid(a.assignmentId,'assignmentId');assertUuid(a.testId,'testId');if(!['group','student'].includes(a.targetType)|| (a.targetType==='group'&&!a.groupId)||(a.targetType==='student'&&!a.accountPlayerId))throw new Error('asignación inválida');if(a.accountPlayerId)assertUuid(a.accountPlayerId,'accountPlayerId');return a;}
function createAttempt(input={}){const ts=now();const a={attemptId:input.attemptId||id(),testId:input.testId,accountPlayerId:input.accountPlayerId,parentAttemptId:input.parentAttemptId||null,status:input.status||'pending',progress:input.progress||{},revision:input.revision||1,startedAt:input.startedAt||null,updatedAt:input.updatedAt||ts,finishedAt:input.finishedAt||null,origin:input.origin||'new',official:false,deletedAt:null};validateAttempt(a);return a;}
function transitionAttempt(attempt,to,{reopened=false}={}){assertTransition('attempt',attempt.status,to);attempt.status=to;attempt.revision++;attempt.updatedAt=now();if(to==='reopened'||reopened)attempt.finishedAt=null;if(to==='deleted')attempt.deletedAt=attempt.updatedAt;return attempt;}
function transitionTest(test,to){assertTransition('test',test.status,to);test.status=to;test.revision++;test.updatedAt=now();return test;}
function createCheckpoint(input={}){const c={checkpointId:input.checkpointId||id(),attemptId:input.attemptId,index:input.index||0,answers:input.answers||[],progress:input.progress||{},effectiveTime:input.effectiveTime||0,version:input.version||1,savedAt:input.savedAt||now()};validateCheckpoint(c);return c;}
function createResult(input={}){const r={resultId:input.resultId||id(),attemptId:input.attemptId,testId:input.testId,accountPlayerId:input.accountPlayerId,score:Number(input.score)||0,correct:Number(input.correct)||0,incorrect:Number(input.incorrect)||0,duration:Number(input.duration)||0,breakdown:input.breakdown||{},completedAt:input.completedAt||now(),rankingPublicationId:input.rankingPublicationId||null,settlementKey:input.settlementKey||null};assertUuid(r.resultId,'resultId');assertUuid(r.attemptId,'attemptId');assertUuid(r.testId,'testId');assertUuid(r.accountPlayerId,'accountPlayerId');return r;}
function createEvent(input={}){const e={eventId:input.eventId||id(),testId:input.testId,attemptId:input.attemptId||null,actor:input.actor||'system',action:input.action||'',reason:input.reason||'',revision:input.revision||1,occurredAt:input.occurredAt||now(),metadata:input.metadata||{}};assertUuid(e.eventId,'eventId');assertUuid(e.testId,'testId');if(e.attemptId)assertUuid(e.attemptId,'attemptId');if(!e.action)throw new Error('action obligatoria');assertJsonSize(e.metadata,MAX_METADATA,'metadata');return e;}
function appendEvent(root,event){if(root.events.some(x=>x.eventId===event.eventId))return false;root.events.push(event);return true;}
function applyRevision(entity, incomingRevision, patch){if(!Number.isInteger(incomingRevision)||incomingRevision<=entity.revision)throw new Error('revisión antigua o duplicada');Object.assign(entity,patch,{revision:incomingRevision,updatedAt:now()});return entity;}
function markOfficial(root,attemptId){const attempt=root.attempts.find(x=>x.attemptId===attemptId);if(!attempt||attempt.status==='deleted')throw new Error('intento no publicable');if(root.attempts.some(x=>x.testId===attempt.testId&&x.accountPlayerId===attempt.accountPlayerId&&x.official&&x.attemptId!==attemptId))throw new Error('ya existe intento oficial');attempt.official=true;attempt.revision++;attempt.updatedAt=now();return attempt;}
module.exports={SCHEMA_VERSION,MAX_SNAPSHOTS,createRoot,createTest,createAssignment,createAttempt,transitionAttempt,transitionTest,createCheckpoint,createResult,createEvent,appendEvent,applyRevision,markOfficial};
