'use strict';
const {createTest,createAssignment,createAttempt,createEvent,appendEvent,applyRevision,transitionTest,transitionAttempt}=require('./testModel');
const {assertUuid,assertIso}=require('./testValidation');
function createTestService({store,actor='admin'}={}){
 if(!store)throw Error('store obligatorio');let root=store.load();const persist=()=>store.save(root);
 const event=(testId,action,attemptId=null,metadata={})=>appendEvent(root,createEvent({testId,attemptId,actor,action,metadata}));
 function list(filters={}){return root.tests.filter(t=>(!filters.status||t.status===filters.status)&&(!filters.creator||t.creator===filters.creator)).map(t=>({...t}));}
 function get(testId){assertUuid(testId,'testId');const t=root.tests.find(x=>x.testId===testId);if(!t)throw Error('prueba no encontrada');return t;}
 function create(input){const t=createTest({...input,status:'draft'});root.tests.push(t);event(t.testId,'test_created');persist();return t;}
 function update(testId,revision,patch){const t=get(testId);if(t.status!=='draft')throw Error('prueba no editable');applyRevision(t,revision,{title:patch.title??t.title,description:patch.description??t.description,configuration:patch.configuration??t.configuration});event(t.testId,'test_updated');persist();return t;}
 function clone(value){return JSON.parse(JSON.stringify(value));}
 function duplicate(testId){const source=get(testId);const t=createTest({title:`${source.title} (copia)`,description:source.description,configuration:clone(source.configuration),creator:source.creator});const assignments=root.assignments.filter(x=>x.testId===testId).map(x=>createAssignment({...clone(x),assignmentId:undefined,testId:t.testId,createdAt:undefined,revision:1}));root.tests.push(t);root.assignments.push(...assignments);event(t.testId,'test_duplicated',null,{sourceTestId:testId,assignmentCount:assignments.length});persist();return {test:t,assignments};}
 function replaceAssignments(testId,items){get(testId);if(!Array.isArray(items)||items.length>500)throw Error('asignaciones inválidas');const next=items.map(x=>createAssignment({...x,testId}));root.assignments=root.assignments.filter(x=>x.testId!==testId);root.assignments.push(...next);event(testId,'assignments_replaced');persist();return next;}
 function schedule(testId,revision,{startsAt,closesAt,entryToleranceMinutes=0}={}){const t=get(testId);assertIso(startsAt,'startsAt');if(closesAt!=null)assertIso(closesAt,'closesAt');if(closesAt&&Date.parse(closesAt)<=Date.parse(startsAt))throw Error('closesAt must follow startsAt');if(!Number.isInteger(entryToleranceMinutes)||entryToleranceMinutes<0||entryToleranceMinutes>1440)throw Error('invalid tolerance');if(revision<=t.revision)throw Error('stale revision');transitionTest(t,'scheduled');Object.assign(t,{startsAt,closesAt,entryToleranceMinutes,revision,updatedAt:new Date().toISOString()});event(testId,'test_scheduled',null,{startsAt,closesAt,entryToleranceMinutes});persist();return t;}
 function start(testId,revision,{now=new Date().toISOString(),force=false}={}){const t=get(testId);assertIso(now,'now');if(revision<=t.revision)throw Error('stale revision');if(t.status==='scheduled'&&!force){const earliest=Date.parse(t.startsAt)-(t.entryToleranceMinutes||0)*60000;if(Date.parse(now)<earliest)throw Error('start too early');}transitionTest(t,'active');t.revision=revision;t.updatedAt=new Date().toISOString();t.configurationSnapshot=clone(t.configuration);event(testId,'test_started',null,{startedAt:now});persist();return t;}
 function cancel(testId,revision){const t=get(testId);if(revision<=t.revision)throw Error('stale revision');transitionTest(t,'cancelled');t.revision=revision;t.updatedAt=new Date().toISOString();event(testId,'test_cancelled');persist();return t;}
 function examProjection(testId){const t=get(testId);if(t.status!=='active')return null;const c=t.configurationSnapshot||t.configuration;return {testId:t.testId,grade:c.grade||'',tables:Array.isArray(c.tables)?clone(c.tables):[],op:c.op||'mult',ops:Array.isArray(c.ops)?clone(c.ops):[],opsConfig:c.opsConfig?clone(c.opsConfig):null,timeLimit:Number(c.timeLimit)||0,total:Number(c.total)||20,startedAt:Date.parse(t.updatedAt)};}
 function isAssigned(testId,accountPlayerId,groupId){return root.assignments.some(a=>a.testId===testId&&((a.targetType==='student'&&a.accountPlayerId===accountPlayerId)||(a.targetType==='group'&&a.groupId===groupId)));}
 function listAttempts(testId,filters={}){get(testId);return root.attempts.filter(a=>a.testId===testId&&(!filters.accountPlayerId||a.accountPlayerId===filters.accountPlayerId)&&(!filters.status||a.status===filters.status)).map(a=>clone(a));}
 function createStudentAttempt({testId,accountPlayerId,studentSnapshot,groupId}){const test=get(testId);assertUuid(accountPlayerId,'accountPlayerId');if(test.status!=='active')throw Error('prueba no activa');if(!isAssigned(testId,accountPlayerId,groupId))throw Error('alumno no asignado');const existing=root.attempts.find(a=>a.testId===testId&&a.accountPlayerId===accountPlayerId&&!['deleted','restarted'].includes(a.status));if(existing)throw Error('intento ya existe');const attempt=createAttempt({testId,accountPlayerId,progress:{studentSnapshot:clone(studentSnapshot||{})}});root.attempts.push(attempt);event(testId,'attempt_created',attempt.attemptId);persist();return attempt;}
 function startStudentAttempt(attemptId,accountPlayerId){assertUuid(attemptId,'attemptId');assertUuid(accountPlayerId,'accountPlayerId');const a=root.attempts.find(x=>x.attemptId===attemptId&&x.accountPlayerId===accountPlayerId);if(!a)throw Error('intento no encontrado');if(a.status==='pending'){transitionAttempt(a,'started');transitionAttempt(a,'in_progress');a.startedAt=a.updatedAt;event(a.testId,'attempt_started',a.attemptId);persist();}return a;}
 return {create,list,get,update,duplicate,replaceAssignments,schedule,start,cancel,examProjection,isAssigned,listAttempts,createStudentAttempt,startStudentAttempt};
}
module.exports={createTestService};
