'use strict';
const {createTest,createAssignment,createAttempt,createResult,createEvent,appendEvent,applyRevision,transitionTest,transitionAttempt}=require('./testModel');
const {assertUuid,assertIso,validateTestConfiguration}=require('./testValidation');
const {validateOpsConfig}=require('../../client/maestro/tableRanges');
const {generateConfiguredQuestions,answerQuestion,scoreFor,clone:cloneFlow}=require('./studentTestFlowService');
function createTestService({store,actor='admin',groupResolver=null}={}){
 if(!store)throw Error('store obligatorio');let root=store.load();const persist=()=>store.save(root);
 const event=(testId,action,attemptId=null,metadata={},eventId)=>appendEvent(root,createEvent({eventId,testId,attemptId,actor,action,metadata}));
 function list(filters={}){return root.tests.filter(t=>(!filters.status||t.status===filters.status)&&(!filters.creator||t.creator===filters.creator)).map(t=>({...t}));}
 function get(testId){assertUuid(testId,'testId');const t=root.tests.find(x=>x.testId===testId);if(!t)throw Error('prueba no encontrada');return t;}
 function nextFolio(){const used=new Set(root.tests.filter(item=>!item.archivedAt).map(item=>Number.parseInt(item.folio,10)).filter(Number.isInteger));let next=1;while(used.has(next))next++;return String(next).padStart(4,'0');}
 function create(input){const folio=input.folio||nextFolio();const creator=input.creator||'00000000-0000-4000-8000-000000000000';const t=createTest({...input,folio,title:folio,creator,status:'draft'});root.tests.push(t);event(t.testId,'test_created');persist();return t;}
 function update(testId,revision,patch){const t=get(testId);if(t.status!=='draft')throw Error('prueba no editable');const configuration=patch.configuration===undefined?t.configuration:{...t.configuration,...patch.configuration,opsConfig:{...(t.configuration?.opsConfig||{}),...(patch.configuration?.opsConfig||{})}};validateTestConfiguration(configuration,{allowIncomplete:true});if(configuration.opsConfig)validateOpsConfig(configuration.opsConfig);applyRevision(t,revision,{title:patch.title??t.title,description:patch.description??t.description,configuration});event(t.testId,'test_updated');persist();return t;}
 function clone(value){return JSON.parse(JSON.stringify(value));}
 function duplicate(testId){const source=get(testId);const t=create({folio:nextFolio(),description:source.description,configuration:clone(source.configuration),creator:source.creator});const assignments=root.assignments.filter(x=>x.testId===testId).map(x=>createAssignment({...clone(x),assignmentId:undefined,testId:t.testId,createdAt:undefined,revision:1}));root.assignments.push(...assignments);event(t.testId,'test_duplicated',null,{sourceTestId:testId,assignmentCount:assignments.length});persist();return {test:t,assignments};}
 function replaceAssignments(testId,items){const test=get(testId);if(['cancelled','finished','closed'].includes(test.status))throw Error('prueba no asignable');if(!Array.isArray(items)||items.length>500)throw Error('asignaciones inválidas');const seen=new Set();const expanded=[];for(const item of items){if(item?.targetType==='group'&&item.expandGroup===true&&typeof groupResolver==='function'){const members=groupResolver(item.groupId);if(members===undefined)throw Error('grupo no encontrado');for(const accountPlayerId of members)expanded.push({...item,targetType:'student',accountPlayerId,expandGroup:undefined});continue;}expanded.push(item);}const next=expanded.map(x=>{const key=`${x.targetType}:${x.targetType==='student'?x.accountPlayerId:x.groupId}`;if(seen.has(key))throw Error('asignación duplicada');seen.add(key);return createAssignment({...x,testId});});root.assignments=root.assignments.filter(x=>x.testId!==testId);root.assignments.push(...next);event(testId,'assignments_replaced',null,{assignmentCount:next.length,groupExpansion:items.some(item=>item?.expandGroup===true)});persist();return next;}
 function listAssignments(testId){get(testId);return root.assignments.filter(a=>a.testId===testId).map(clone);}
 function schedule(testId,revision,{startsAt,closesAt,entryToleranceMinutes=0}={}){const t=get(testId);assertIso(startsAt,'startsAt');if(closesAt!=null)assertIso(closesAt,'closesAt');if(closesAt&&Date.parse(closesAt)<=Date.parse(startsAt))throw Error('closesAt must follow startsAt');if(!Number.isInteger(entryToleranceMinutes)||entryToleranceMinutes<0||entryToleranceMinutes>1440)throw Error('invalid tolerance');if(revision<=t.revision)throw Error('stale revision');transitionTest(t,'scheduled');Object.assign(t,{startsAt,closesAt,entryToleranceMinutes,revision,updatedAt:new Date().toISOString()});event(testId,'test_scheduled',null,{startsAt,closesAt,entryToleranceMinutes});persist();return t;}
 function start(testId,revision,{now=new Date().toISOString(),force=false}={}){const t=get(testId);assertIso(now,'now');if(revision<=t.revision)throw Error('stale revision');if(t.status==='scheduled'&&!force){const earliest=Date.parse(t.startsAt)-(t.entryToleranceMinutes||0)*60000;if(Date.parse(now)<earliest)throw Error('start too early');}transitionTest(t,'active');t.revision=revision;t.updatedAt=new Date().toISOString();t.configurationSnapshot=clone(t.configuration);event(testId,'test_started',null,{startedAt:now});persist();return t;}
 function pause(testId,revision){const t=get(testId);if(revision<=t.revision)throw Error('stale revision');transitionTest(t,'paused');t.revision=revision;t.updatedAt=new Date().toISOString();event(testId,'test_paused');persist();return t;}
 function resume(testId,revision){const t=get(testId);if(revision<=t.revision)throw Error('stale revision');transitionTest(t,'active');t.revision=revision;t.updatedAt=new Date().toISOString();event(testId,'test_resumed');persist();return t;}
 function close(testId,revision){const t=get(testId);if(revision<=t.revision)throw Error('stale revision');transitionTest(t,'closed');t.revision=revision;t.updatedAt=new Date().toISOString();event(testId,'test_closed');persist();return t;}
 function finish(testId,revision){const t=get(testId);if(revision<=t.revision)throw Error('stale revision');transitionTest(t,'finished');t.revision=revision;t.updatedAt=new Date().toISOString();event(testId,'test_finished');persist();return t;}
 function finishLegacy(testId,revision,reason){const t=get(testId);if(t.status!=='draft')throw Error('solo se pueden cerrar borradores historicos');if(revision<=t.revision)throw Error('stale revision');t.status='finished';t.revision=revision;t.updatedAt=new Date().toISOString();event(testId,'test_finished',null,{legacyRecovery:true,reason:String(reason||'').trim()});persist();return t;}
 function archive(testId,revision){const t=get(testId);if(t.status!=='finished')throw Error('solo se pueden archivar pruebas finalizadas');if(t.archivedAt)throw Error('la prueba ya esta archivada');if(revision!==undefined&&(!Number.isInteger(revision)||revision<=t.revision))throw Error('stale revision');t.archivedAt=new Date().toISOString();t.revision=(revision||t.revision+1);t.updatedAt=t.archivedAt;event(testId,'test_archived');persist();return t;}
 function cancel(testId,revision){const t=get(testId);if(revision<=t.revision)throw Error('stale revision');transitionTest(t,'cancelled');t.revision=revision;t.updatedAt=new Date().toISOString();event(testId,'test_cancelled');persist();return t;}
 function examProjection(testId){const t=get(testId);if(t.status!=='active')return null;const c=t.configurationSnapshot||t.configuration;return {testId:t.testId,grade:c.grade||'',tables:Array.isArray(c.tables)?clone(c.tables):[],op:c.op||'mult',ops:Array.isArray(c.ops)?clone(c.ops):[],opsConfig:c.opsConfig?clone(c.opsConfig):null,timeLimit:Number(c.timeLimit)||0,total:Number(c.total)||20,startedAt:Date.parse(t.updatedAt)};}
 function isAssigned(testId,accountPlayerId,groupId){return root.assignments.some(a=>a.testId===testId&&((a.targetType==='student'&&a.accountPlayerId===accountPlayerId)||(a.targetType==='group'&&a.groupId===groupId)));}
 function listAttempts(testId,filters={}){get(testId);return root.attempts.filter(a=>a.testId===testId&&(!filters.accountPlayerId||a.accountPlayerId===filters.accountPlayerId)&&(!filters.status||a.status===filters.status)).map(a=>clone(a));}
 function findStudentAttempt(testId,attemptId,accountPlayerId){assertUuid(testId,'testId');assertUuid(attemptId,'attemptId');assertUuid(accountPlayerId,'accountPlayerId');const a=root.attempts.find(x=>x.testId===testId&&x.attemptId===attemptId&&x.accountPlayerId===accountPlayerId);if(!a)throw Error('intento no encontrado');return a;}
 function createStudentAttempt({testId,accountPlayerId,studentSnapshot,groupId}){const test=get(testId);assertUuid(accountPlayerId,'accountPlayerId');if(test.status!=='active')throw Error('prueba no activa');if(!isAssigned(testId,accountPlayerId,groupId))throw Error('alumno no asignado');const existing=root.attempts.find(a=>a.testId===testId&&a.accountPlayerId===accountPlayerId&&!['deleted','restarted'].includes(a.status));if(existing)throw Error('intento ya existe');const snapshot=clone(test.configurationSnapshot||test.configuration);const questions=generateConfiguredQuestions(snapshot);const attempt=createAttempt({testId,accountPlayerId,configurationSnapshot:snapshot,progress:{studentSnapshot:clone(studentSnapshot||{}),questions,answers:[],currentIndex:0,correct:0,incorrect:0,score:0,totalQuestions:questions.length}});root.attempts.push(attempt);event(testId,'attempt_created',attempt.attemptId);persist();return attempt;}
 function startStudentAttempt(attemptId,accountPlayerId){assertUuid(attemptId,'attemptId');assertUuid(accountPlayerId,'accountPlayerId');const a=root.attempts.find(x=>x.attemptId===attemptId&&x.accountPlayerId===accountPlayerId);if(!a)throw Error('intento no encontrado');if(a.status==='pending'){transitionAttempt(a,'started');transitionAttempt(a,'in_progress');a.startedAt=a.updatedAt;event(a.testId,'attempt_started',a.attemptId);persist();}return a;}
 function answerStudentQuestion({testId,attemptId,accountPlayerId,questionId,answer,eventId}){const a=findStudentAttempt(testId,attemptId,accountPlayerId);if(!['in_progress','reconnected'].includes(a.status))throw Error('intento no activo');if(eventId){const prior=root.events.find(item=>item.eventId===eventId);if(prior){if(prior.attemptId!==attemptId||prior.action!=='answer_submitted'||prior.metadata.questionId!==questionId||String(prior.metadata.answer)!==String(answer))throw Error('eventId contradictorio');return {attempt:a,duplicate:true,correct:prior.metadata.correct};}assertUuid(eventId,'eventId');}const p=a.progress||{};const questions=Array.isArray(p.questions)?p.questions:[];const index=Number.isInteger(p.currentIndex)?p.currentIndex:0;const question=questions.find(item=>item.questionId===questionId);if(!question)throw Error('pregunta no encontrada');if(!Array.isArray(p.answers))p.answers=[];if(p.answers.some(item=>item.questionId===questionId))throw Error('pregunta ya respondida');const correct=answerQuestion(question,answer);p.answers.push({questionId,answer,corrected:correct});p.correct=Number(p.correct||0)+(correct?1:0);p.incorrect=Number(p.incorrect||0)+(correct?0:1);p.score=scoreFor(p.correct,a.configurationSnapshot?.multiplier);p.currentIndex=Math.min(index+1,questions.length);a.progress=p;a.revision++;a.updatedAt=new Date().toISOString();event(a.testId,'answer_submitted',a.attemptId,{eventId,questionId,answer,correct},eventId);persist();return {attempt:a,duplicate:false,correct};}
 function disconnectStudentAttempt({testId,attemptId,accountPlayerId}){const a=findStudentAttempt(testId,attemptId,accountPlayerId);if(a.status==='in_progress')transitionAttempt(a,'disconnected');persist();return a;}
 function reconnectStudentAttempt({testId,attemptId,accountPlayerId}){const a=findStudentAttempt(testId,attemptId,accountPlayerId);if(a.status==='disconnected'){transitionAttempt(a,'reconnected');transitionAttempt(a,'in_progress');}persist();return a;}
 function finishStudentAttempt({testId,attemptId,accountPlayerId,eventId}){const a=findStudentAttempt(testId,attemptId,accountPlayerId);const existing=root.results.find(item=>item.attemptId===attemptId);if(existing)return {attempt:a,result:existing,duplicate:true};if(!['in_progress','reconnected'].includes(a.status))throw Error('intento no finalizable');if(eventId){const prior=root.events.find(item=>item.eventId===eventId);if(prior){if(prior.attemptId!==attemptId||prior.action!=='attempt_finished')throw Error('eventId contradictorio');return {attempt:a,result:root.results.find(item=>item.attemptId===attemptId),duplicate:true};}assertUuid(eventId,'eventId');}transitionAttempt(a,'finished');a.finishedAt=a.updatedAt;const p=a.progress||{};const result=createResult({testId,attemptId,accountPlayerId,score:p.score,correct:p.correct,incorrect:p.incorrect,total:p.totalQuestions,complete:true,breakdown:{multiplier:a.configurationSnapshot?.multiplier||1}});root.results.push(result);event(testId,'attempt_finished',attemptId,{eventId,resultId:result.resultId},eventId);persist();return {attempt:a,result,duplicate:false};}
 function recordLiveExamProgress({testId,accountPlayerId,studentSnapshot,message}={}){const test=get(testId);assertUuid(accountPlayerId,'accountPlayerId');const examStartedAt=message?.examStartedAt;if(!examStartedAt)return {attempt:null,duplicate:false};const now=new Date().toISOString(),total=Number(message?.totalQ??message?.total)||0,index=Math.max(0,Number(message?.qIndex??message?.currentIndex)||0),correct=Math.max(0,Number(message?.correct)||0),incorrect=Math.max(0,Number(message?.wrong??message?.incorrect)||0),progress={studentSnapshot:clone(studentSnapshot||{}),examStartedAt,currentIndex:index,totalQuestions:total,correct,incorrect,score:Number(message?.score)||0};let attempt=root.attempts.find(a=>a.testId===testId&&a.accountPlayerId===accountPlayerId&&a.origin==='live_exam'&&a.progress?.examStartedAt===examStartedAt);if(!attempt){attempt=createAttempt({testId,accountPlayerId,status:'in_progress',origin:'live_exam',configurationSnapshot:clone(test.configurationSnapshot||test.configuration),startedAt:new Date(Number(examStartedAt)).toISOString(),updatedAt:now,progress});root.attempts.push(attempt);event(testId,'attempt_created',attempt.attemptId,{origin:'live_exam',live:true});}else if(!['finished','deleted'].includes(attempt.status)){attempt.status='in_progress';attempt.progress=progress;attempt.updatedAt=now;attempt.revision++;}persist();return {attempt,duplicate:false};}
 function recordLiveExamResult({testId,accountPlayerId,studentSnapshot,message}={}){const test=get(testId);assertUuid(accountPlayerId,'accountPlayerId');const existing=root.attempts.find(a=>a.testId===testId&&a.accountPlayerId===accountPlayerId&&a.origin==='live_exam'&&a.progress?.examStartedAt===message?.examStartedAt);const now=new Date().toISOString(),total=Number(message?.total)||0,correct=Number(message?.correct)||0,incorrect=Number(message?.wrong??message?.incorrect)||Math.max(0,total-correct);if(existing){const prior=root.results.find(item=>item.attemptId===existing.attemptId);if(prior)return {attempt:existing,result:prior,duplicate:true};existing.status='finished';existing.finishedAt=now;existing.updatedAt=now;existing.progress={...(existing.progress||{}),studentSnapshot:clone(studentSnapshot||existing.progress?.studentSnapshot||{}),currentIndex:total,totalQuestions:total,correct,incorrect,score:Number(message?.score)||0};const result=createResult({testId,attemptId:existing.attemptId,accountPlayerId,score:existing.progress.score,correct,incorrect,total,complete:true,duration:Number(message?.durationMs)||0,breakdown:{multiplier:existing.configurationSnapshot?.multiplier||1}});root.results.push(result);event(testId,'attempt_finished',existing.attemptId,{resultId:result.resultId,origin:'live_exam'});persist();return {attempt:existing,result,duplicate:false};}const attempt=createAttempt({testId,accountPlayerId,status:'finished',origin:'live_exam',configurationSnapshot:clone(test.configurationSnapshot||test.configuration),startedAt:message?.examStartedAt?new Date(Number(message.examStartedAt)).toISOString():null,updatedAt:now,finishedAt:now,progress:{studentSnapshot:clone(studentSnapshot||{}),examStartedAt:message?.examStartedAt||null,currentIndex:total,totalQuestions:total,correct,incorrect,score:Number(message?.score)||0}});const result=createResult({testId,attemptId:attempt.attemptId,accountPlayerId,score:attempt.progress.score,correct,incorrect,total,complete:true,duration:Number(message?.durationMs)||0,breakdown:{multiplier:attempt.configurationSnapshot?.multiplier||1}});root.attempts.push(attempt);root.results.push(result);event(testId,'attempt_created',attempt.attemptId,{origin:'live_exam'});event(testId,'attempt_finished',attempt.attemptId,{resultId:result.resultId,origin:'live_exam'});persist();return {attempt,result,duplicate:false};}
 function replaceAssignmentsWithGroups(testId,items){const test=get(testId);if(['cancelled','finished','closed'].includes(test.status))throw Error('prueba no asignable');if(!Array.isArray(items)||items.length>500)throw Error('asignaciones invalidas');const explicitStudents=new Set(items.filter(item=>item?.targetType==='student'&&item.accountPlayerId).map(item=>item.accountPlayerId));const expanded=[];for(const item of items){if(item?.targetType==='group'&&item.expandGroup===true&&typeof groupResolver==='function'){const members=groupResolver(item.groupId);if(members===undefined)throw Error('grupo no encontrado');expanded.push({...item,expandGroup:undefined});for(const accountPlayerId of members)if(!explicitStudents.has(accountPlayerId))expanded.push({...item,targetType:'student',accountPlayerId,sourceGroupId:item.groupId,expandGroup:undefined});}else expanded.push(item);}const seen=new Set();const next=expanded.map(item=>{const key=`${item.targetType}:${item.targetType==='student'?item.accountPlayerId:item.groupId}`;if(seen.has(key))throw Error('asignacion duplicada');seen.add(key);const assignment=createAssignment({...item,testId});if(item.sourceGroupId)assignment.sourceGroupId=item.sourceGroupId;return assignment;});root.assignments=root.assignments.filter(item=>item.testId!==testId);root.assignments.push(...next);event(testId,'assignments_replaced',null,{assignmentCount:next.length,groupExpansion:items.some(item=>item?.targetType==='group'&&item.expandGroup===true)});persist();return next;}
 return {create,list,get,update,duplicate,replaceAssignments:replaceAssignmentsWithGroups,listAssignments,schedule,start,pause,resume,close,finish,finishLegacy,archive,cancel,examProjection,isAssigned,listAttempts,createStudentAttempt,startStudentAttempt,getStudentAttempt:findStudentAttempt,answerStudentQuestion,disconnectStudentAttempt,reconnectStudentAttempt,finishStudentAttempt,recordLiveExamProgress,recordLiveExamResult};
}
module.exports={createTestService};
